name: AMDGT
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13  
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8_0
  - torchvision=0.15.2=py310_cu118
  - torchaudio=2.0.2=py310_cu118
  - cudatoolkit=11.8  
  - numpy=1.24.4  
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - numexpr=2.8.4 
  - blas=1.0=mkl
  - mkl=2023.2.0  
  - intel-openmp=2023.2.0  
  - zlib=1.2.13  
  - tk=8.6.13
  - xz=5.4.2 
  - typing_extensions=4.7.1  
  - pip=23.3.1
  - pip:
    - dgl-cu118==0.9.2  
    - https://data.dgl.ai/wheels/dgl_cu118-0.9.2-cp310-cp310-win_amd64.whl